document.addEventListener('DOMContentLoaded', () => {
    // 8. Translation (i18n) Engine
    const translations = {
        pt: {
            nav_home: "Início",
            nav_courses: "Cursos",
            nav_about: "Quem Somos",
            nav_team: "Equipe",
            nav_conduct: "Código de Conduta",
            nav_contact: "Contato",
            btn_login: "Entrar",
            btn_speak_team: "Falar com a Equipe",
            hero_title: "Educação corporativa, liderança<br />e gestão para empresas<br />em <span class=\"text-accent\">crescimento.</span>",
            hero_desc: "Cursos online e experiências presenciais que desenvolvem<br />pessoas, fortalecem líderes e impulsionam resultados.",
            hero_btn_explore: "Explorar Cursos <i class=\"ph ph-arrow-right\"></i>",
            hero_benefit_1: "Cursos 100% Online<br />e Presenciais",
            hero_benefit_2: "Instrutores<br />Especialistas",
            hero_benefit_3: "Conteúdo Aplicável<br />à sua Reality",
            hero_benefit_4: "Certificado<br />Reconhecido",
            hero_mobile_title: "Conhecimento<br />que <span class=\"text-accent\">transforma.</span><br />Resultados que<br /><span class=\"text-accent\">impulsionam.</span>",
            hero_mobile_desc: "Formação prática, atualizada e estratégica para você evoluir, liderar e gerar impacto no mercado.",
            hero_mobile_btn: "Conheça nossos cursos <i class=\"ph ph-arrow-right\"></i>",
            hero_mobile_benefit_1: "Conteúdo<br />atualizado",
            hero_mobile_benefit_2: "Aprendizado<br />aplicável",
            hero_mobile_benefit_3: "Certificados<br />reconhecidos",
            hero_mobile_benefit_4: "Comunidade<br />ativa",
            hero_mobile_footer_1: "APRENDA COM <span class=\"text-accent-alt\">ESPECIALISTAS</span>",
            hero_mobile_footer_2: "APLIQUE NA <span class=\"text-accent-alt\">PRÁTICA</span>",
            hero_mobile_footer_3: "EVOLUA <span class=\"text-accent-alt\">SEMPRE</span>",
            trilhas_section_title: "Nossas Trilhas",
            trilhas_see_all: "Ver todos os cursos <i class=\"ph ph-arrow-right\"></i>",
            trilha_1_title: "Liderança",
            trilha_1_desc: "Desenvolva líderes inspiradores e times de alta performance.",
            trilha_2_title: "Gestão de Pessoas",
            trilha_2_desc: "Engajamento, cultura e performance que geram valor.",
            trilha_3_title: "Planejamento Estratégico",
            trilha_3_desc: "Transforme estratégia em ação e resultados sustentáveis.",
            trilha_4_title: "Merchandising no PDV",
            trilha_4_desc: "Técnicas e práticas para impulsionar vendas e experiência no ponto de venda.",
            trilha_5_title: "Desenvolvimento Humano",
            trilha_5_desc: "Autoconhecimento, comunicação e inteligência emocional.",
            about_label: "Quem Somos",
            about_title: "Transformando potencial de líderes e organizações em <span class=\"text-accent\">resultados reais.</span>",
            about_desc_1: "A AXIA GROUP | ACADEMY é um ecossistema de educação corporativa focado em impulsionar a performance de médias e grandes empresas. Unimos a experiência prática de mercado com metodologias de ensino ágeis e aplicáveis.",
            about_desc_2: "Nossa atuação abrange desde o desenvolvimento de líderes de alto impacto até a reestruturação de processos e planejamento de negócios, integrando tecnologia, cultura de resultados e governança sólida.",
            stat_experience: "Anos de experiência",
            stat_leaders: "Líderes formados",
            stat_companies: "Empresas parceiras",
            mvv_label: "Nossos Pilares",
            mvv_section_title: "O que nos move e direciona",
            mvv_section_subtitle: "Guiados por propósitos claros, objetivos audaciosos e valores sólidos para entregar a melhor experiência de aprendizagem.",
            mvv_missao_title: "Missão",
            mvv_missao_desc: "Prestar serviços de excelência e procurar, de forma contínua e sistemática, sanar <br />as necessidades dos nossos clientes, superando as suas expectativas e contribuindo dessa forma para a<br /> geração de valor.",
            mvv_missao_tag: "Propósito &amp; Ação",
            mvv_visao_title: "Visão",
            mvv_visao_desc: "Estar entre as principais empresas do mercado de serviços de consultoria e gestão, e sermos uma referência de excelência na prestação de serviços de apoio à gestão empresarial.",
            mvv_visao_tag: "Foco no Futuro",
            mvv_valores_title: "Valores",
            mvv_valores_desc: "Pautados por ética, honestidade e transparência nas relações. Buscamos a qualidade e a excelência contínua com responsabilidade social, foco em sustentabilidade e entrega pontual de resultados.",
            mvv_valores_tag: "Nossos Princípios",
            incompany_label: "Compromisso com o Agronegócio",
            incompany_title: "Conectando Lideranças para Fortalecer o Futuro da Agroindústria",
            incompany_description: "Nosso compromisso é capacitar produtores e indústrias para impulsionar a verticalização regional, promovendo o desenvolvimento sustentável por meio de conexões estratégicas, tecnologia e inteligência de mercado.",
            incompany_feature_1_title: "Alianças e Conexões Estratégicas",
            incompany_feature_1_desc: "Participação activa em debates setoriais para consolidar parcerias fundamentais ao avanço socioeconómico regional.",
            incompany_feature_2_title: "Tecnologia Aplicada ao Campo",
            incompany_feature_2_desc: "Integração de inovações e processos modernos que ampliam a produtividade e a competitividade do produtor rural.",
            incompany_feature_3_title: "Verticalização da Produção",
            incompany_feature_3_desc: "Apoio no planejamento industrial para reter valor na região, transformando a produção primária em produtos manufaturados de alto valor.",
            incompany_feature_4_title: "Desenvolvimento Sustentável",
            incompany_feature_4_desc: "Estruturação de estratégias inteligentes de mercado que alinham crescimento econômico a práticas de preservação de longo prazo.",
            incompany_btn: "Falar com a Nossa Equipe <i class=\"ph ph-arrow-right\"></i>",
            incompany_vertical_text: "AGRO &amp; INOVAÇÃO",
            platform_label: "App da Empresa",
            platform_title: "Mais praticidade na <span class=\"text-highlight\">palma da sua mão</span>",
            platform_description: "Com o nosso aplicativo, você acompanha tudo o que precisa de onde estiver, com segurança, agilidade e uma experiência completa.",
            platform_feature_1: "Acompanhe suas informações em tempo real",
            platform_feature_2: "Relatórios e indicadores de forma simples e rápida",
            platform_feature_3: "Notificações importantes na hora certa",
            platform_feature_4: "Segurança e proteção dos seus dados",
            cert_label: "Garantia de Excelência",
            cert_title: "Nossos Selos e Certificações",
            cert_subtitle: "Nossas práticas corporativas e programas de capacitação são chancelados por selos de excelência, assegurando conformidade legal, diversidade, integridade e governança de alto nível.",
            cert_zoom: "<i class=\"ph ph-magnifying-glass-plus\"></i> Ampliar Selo",
            cert_1_title: "Selo Abrangem",
            cert_1_desc: "Padrão nacional reconhecido na gestão e qualidade de treinamentos corporativos de excelência.",
            cert_2_title: "Certificação LGPD",
            cert_2_desc: "Conformidade completa e segurança de dados auditada sob as diretrizes da legislação nacional.",
            cert_3_title: "Liderança Feminina",
            cert_3_desc: "Fomento ativo e comprovado à igualdade de gênero, equidade e inclusão no ambiente de trabalho.",
            cert_4_title: "Responsabilidade Social",
            cert_4_desc: "Práticas sustentáveis certificadas de governança ambiental, social e corporativa (ESG).",
            cert_5_title: "Conformidade Trabalhista",
            cert_5_desc: "Rigores éticos e conformidade legal assegurada nas relações de trabalho e contratações.",
            footer_desc: "Educação corporativa, liderança e gestão para empresas em crescimento.",
            footer_links_title: "Links rápidos",
            footer_categories_title: "Categorias",
            footer_contact_title: "Entre em contato",
            team_section_title: "Corpo Diretor & Liderança",
            team_role_1: "Fundador & CEO",
            team_focus_1: "Planejamento, Análises e Inspeções Internacionais",
            team_bio_1_p1: "CEO da Axia Group, empresa de consultoria e gestão empresarial que atua no Brasil e no exterior e tem em seu DNA visão de futuro, foco em resultados e soluções inovadoras que garantem os mais altos níveis de valor.",
            team_bio_1_p2: "Possui sólida experiência e liderança em projetos TAP/PID (project charter / Project Initiation Document) “projetos iniciados do zero”, com especialização em gestão de operações da indústria, do comércio e do agronegócio, focando em inovação, tecnologia e sustentabilidade.",
            team_bio_1_li1: "Bacharel em Administração de Empresas pela Faculdade Pitágoras (Campus Linhares - ES).",
            team_bio_1_li2: "MBA em Auditoria, Controladoria e Finanças Empresariais pela FGV (Fundação Getúlio Vargas).",
            team_bio_1_li3: "Consultor membro da clínica de negócios do CRA/ES (Conselho Regional de Administração do Espírito Santo).",
            team_bio_1_li4: "Consultor empresarial cadastrado na ABRACEM (Associação Brasileira de Consultores Empresariais).",
            team_cta_schedule: "<i class=\"fa-brands fa-whatsapp\"></i> Agende um Horário",
            team_role_2: "Diretor de Marketing",
            team_focus_2: "Planejamento e Estratégias de Publicidade e Marketing",
            team_bio_2_p1: "Administrador, publicitário e empreendedor com forte atuação no Brasil e em Portugal. Capixaba, reside entre Serra/ES e Lisboa/PT, acumulando mais de 25 anos de experiência nos setores de marketing digital, gestão empresarial e comunicação estratégica.",
            team_bio_2_p2: "É fundador e CEO da Divulgar Comunicação, agência de publicidade e marketing digital com sedes no Brasil e em Portugal, reconhecida por desenvolver soluções criativas e eficazes que conectam marcas ao seu público de forma autêntica e estratégica.",
            team_bio_2_p3: "Com uma abordagem inovadora, atua no desenvolvimento de projetos que aliam tradição e modernidade, com foco na experiência do cliente e no fortalecimento de marcas. Possui especial expertise em:",
            team_bio_2_li1: "Consultoria em marketing digital e branding.",
            team_bio_2_li2: "Estratégias de presença digital (Google, redes sociais e e-commerce).",
            team_bio_2_li3: "Criação e otimização de sites e plataformas digitais.",
            team_bio_2_li4: "Organização de eventos promocionais, parcerias estratégicas e campanhas de sorteio nacionais e internacionais.",
            team_cta_click_here: "<i class=\"fa-brands fa-whatsapp\"></i> Clique Aqui",
            team_role_3: "Diretor Contábil e Jurídico",
            team_focus_3: "Consultoria Contábil, Fiscal e Tributária",
            team_bio_3_p1: "Gilberto Batista atua como Diretor na Controltech Contabilidade e Auditoria S/A, empresa com forte presença no Brasil e nos Estados Unidos.",
            team_bio_3_p2: "À frente da Controltech, lidera uma equipe de alta performance especializada na prestação de serviços completos em consultoria contábil, fiscal, tributária, trabalhista e institucional.",
            team_bio_3_p3: "Com uma visão estratégica e foco em excelência técnica, ele conduz projetos que envolvem desde a análise e estruturação contábil até a revisão fiscal e planejamento tributário, garantindo soluções integradas, conformidade legal e suporte gerencial para empresas de diversos portes e segmentos.",
            team_role_4: "Diretor de Investimentos",
            team_focus_4: "Crédito Estruturado e Relacionamento Bancário",
            team_bio_4_p1: "Formado em Finanças com uma trajetória consolidada de mais de duas décadas no setor bancário e de consultoria empresarial. Atuou como gerente em importantes instituições financeiras, incluindo o Banco Francês e Italiano, Banco Sudameris Brasil, Banco Real ABN AMRO, Banco Santander e Banco Original.",
            team_bio_4_p2: "Fundador da NJCA Consultoria, Newton é especialista em estruturar soluções financeiras personalizadas para captação de recursos e investimentos corporativos seguros.",
            team_bio_4_p3: "Possui um sólido networking corporativo e atua como parceiro de consultoria de renomadas instituições como Banco Inter, Banco PAN, Banco Bari, Banco CashMe e Caixa Econômica Federal. Sua missão é apoiar empresários a tomarem decisões mais inteligentes e rentáveis.",
            team_section_title_2: "Alianças Estratégicas & Mercado Externo",
            team_role_5: "Parceiro de Aliança Estratégica",
            team_focus_5: "Logística e Comércio Exterior Internacional",
            team_bio_5_p1: "Ado Pereira Alves Belmok possui formação técnica em Contabilidade e reside na cidade do Porto, em Portugal, de onde lidera as operações internacionais da Exporto Commerce Ltda.",
            team_bio_5_p2: "Como CEO da Exporto Commerce, comanda uma operação com atuação global e matriz localizada em Cariacica (ES), direcionada ao atendimento estratégico de mercados na América do Norte, América do Sul, Europa e Ásia.",
            team_bio_5_p3: "Tornou-se referência em soluções logísticas e estratégias de exportação, apoiando empresas brasileiras no alcance de novos mercados internacionais de forma segura, com destaque em:",
            team_bio_5_li1: "Captação de fornecedores no Brasil e clientes no exterior.",
            team_bio_5_li2: "Logística completa de exportação e desembaraço aduaneiro.",
            team_bio_5_li3: "Recepção, envio, distribuição e venda de produtos no mercado internacional.",
            team_cta_speak_expert: "<i class=\"fa-brands fa-whatsapp\"></i> Falar com o Especialista",
            conduct_page_title: "Código de Conduta - AXIA GROUP | ACADEMY",
            conduct_hero_title: "Código de Conduta",
            conduct_hero_desc: "Nossos compromissos com a ética, a integridade e a responsabilidade em todas as nossas ações e relacionamentos.",
            conduct_sidebar_title: "Navegação",
            conduct_download_title: "Código de Conduta Completo",
            conduct_download_desc: "Baixe a versão oficial em formato PDF para leitura offline.",
            conduct_download_btn: "Baixar PDF",
            conduct_intro_p: "O Código de Conduta da Axia Group expressa nossos compromissos com a ética, a integridade e a responsabilidade em todas as nossas ações e relacionamentos. Ele orienta o comportamento de todos os colaboradores, parceiros, sócios, fornecedores e demais partes interessadas, reforçando os valores que sustentam nossa atuação.",
            conduct_nav_1: "Saúde e Segurança",
            conduct_nav_2: "Conflito de Interesse",
            conduct_nav_3: "Contratação de Parentes",
            conduct_nav_4: "Informações Confidenciais",
            conduct_nav_5: "Relações Societárias",
            conduct_nav_6: "Clientes e Fornecedores",
            conduct_nav_7: "Setor Público",
            conduct_nav_8: "Relações com a Concorrência",
            conduct_nav_9: "Relações com a Comunidade",
            conduct_nav_10: "Relações com a Mídia",
            conduct_nav_11: "Sustentabilidade",
            conduct_nav_12: "Proteção de Dados",
            conduct_nav_13: "Respeito e Diversidade",
            conduct_nav_14: "Transparência",
            conduct_nav_15: "Cumprimento e Penalidades",
            conduct_title_1: "1.1. Saúde e Segurança",
            conduct_title_2: "1.2. Conflito de Interesse",
            conduct_title_3: "1.3. Contratação de Familiares e Parentes",
            conduct_title_4: "1.4. Informações Confidenciais",
            conduct_title_5: "2. Relações com Sócios/Acionistas e Conselho Consultivo",
            conduct_title_6: "3. Relações com Clientes e Fornecedores",
            conduct_title_6_1: "Brindes e Presentes:",
            conduct_title_6_2: "Interações com Clientes:",
            conduct_title_7: "4. Relações com Setor Público",
            conduct_title_8: "5. Relações com a Concorrência",
            conduct_title_9: "6. Relações com a Comunidade",
            conduct_title_10: "7. Relações com a Mídia",
            conduct_title_11: "8. Sustentabilidade",
            conduct_title_12: "9. Proteção de Dados",
            conduct_title_13: "10. Respeito no Ambiente de Trabalho",
            conduct_title_14: "11. Transparência",
            conduct_title_15: "12. Cumprimento e Penalidades",
            ethics_box_title: "Canais de Ética e Compliance",
            ethics_box_desc: "Caso tenha alguma dúvida ou queira registrar uma reclamação/denúncia formal de forma totalmente confidencial e segura, utilize nossos canais oficiais listados abaixo.",
            ethics_info_title: "Contatos Oficiais",
            ethics_item_email: "E-mail:",
            ethics_item_phone: "Telefone:",
            ethics_item_web: "Plataforma Online:",
            ethics_form_title: "Registrar Reclamação",
            ethics_label_name: "Nome (Opcional)",
            ethics_label_email: "E-mail para Retorno (Opcional)",
            ethics_label_msg: "Relato da Ocorrência/Reclamação",
            ethics_btn_submit: "Enviar Relato",
            contact_hero_title: "Fale Conosco",
            contact_hero_desc: "Estamos prontos para atender você e sua empresa. Escolha o canal de sua preferência.",
            contact_general_title: "Dúvidas, Parcerias e Informações",
            contact_general_desc: "Para falar sobre nossos cursos, agendar reuniões, parcerias de negócios ou outras dúvidas gerais.",
            contact_general_form_title: "Enviar Mensagem",
            contact_label_name: "Nome Completo",
            contact_label_email: "E-mail Corporativo",
            contact_label_phone: "Telefone / WhatsApp",
            contact_label_msg: "Mensagem ou Dúvida",
            contact_btn_send: "Enviar Mensagem",
            contact_info_office: "Nossos Escritórios",
            contact_form_intro: "Preencha o formulário e entraremos em contato em breve."
        },
        es: {
            nav_home: "Inicio",
            nav_courses: "Cursos",
            nav_about: "Quiénes Somos",
            nav_team: "Equipo",
            nav_conduct: "Código de Conducta",
            nav_contact: "Contacto",
            btn_login: "Iniciar Sesión",
            btn_speak_team: "Hablar con el Equipo",
            hero_title: "Educación corporativa, liderazgo<br />y gestión para empresas en<br /><span class=\"text-accent\">crecimiento.</span>",
            hero_desc: "Cursos online y experiencias presenciales que desarrollan<br />personas, fortalecen líderes e impulsan resultados.",
            hero_btn_explore: "Explorar Cursos <i class=\"ph ph-arrow-right\"></i>",
            hero_benefit_1: "Cursos 100% Online<br />y Presenciales",
            hero_benefit_2: "Instructores<br />Expertos",
            hero_benefit_3: "Contenido Aplicable<br />a su Realidad",
            hero_benefit_4: "Certificado<br />Reconocido",
            hero_mobile_title: "Conocimiento<br />que <span class=\"text-accent\">transforma.</span><br />Resultados que<br /><span class=\"text-accent\">impulsan.</span>",
            hero_mobile_desc: "Formación práctica, actualizada y estratégica para que evoluciones, lideres y generes impacto en el mercado.",
            hero_mobile_btn: "Conozca nuestros cursos <i class=\"ph ph-arrow-right\"></i>",
            hero_mobile_benefit_1: "Contenido<br />actualizado",
            hero_mobile_benefit_2: "Aprendizaje<br />aplicable",
            hero_mobile_benefit_3: "Certificados<br />reconocidos",
            hero_mobile_benefit_4: "Comunidad<br />activa",
            hero_mobile_footer_1: "APRENDA CON <span class=\"text-accent-alt\">ESPECIALISTAS</span>",
            hero_mobile_footer_2: "APLIQUE EN LA <span class=\"text-accent-alt\">PRÁCTICA</span>",
            hero_mobile_footer_3: "EVOLUCIONE <span class=\"text-accent-alt\">SIEMPRE</span>",
            trilhas_section_title: "Nuestras Rutas",
            trilhas_see_all: "Ver todos los cursos <i class=\"ph ph-arrow-right\"></i>",
            trilha_1_title: "Liderazgo",
            trilha_1_desc: "Desarrolle líderes inspiradores y equipos de alto rendimiento.",
            trilha_2_title: "Gestión de Personas",
            trilha_2_desc: "Compromiso, cultura y rendimiento que generan valor.",
            trilha_3_title: "Planeamiento Estratégico",
            trilha_3_desc: "Transforme la estrategia en acción y resultados sostenibles.",
            trilha_4_title: "Merchandising en el PDV",
            trilha_4_desc: "Técnicas y prácticas para impulsar ventas y experiencia en el punto de venta.",
            trilha_5_title: "Desarrollo Humano",
            trilha_5_desc: "Autoconocimiento, comunicación e inteligencia emocional.",
            about_label: "Quiénes Somos",
            about_title: "Transformando el potencial de líderes y organizaciones en <span class=\"text-accent\">resultados reales.</span>",
            about_desc_1: "AXIA GROUP | ACADEMY es un ecosistema de educación corporativa enfocado en impulsar el desempeño de medianas y grandes empresas. Combinamos la experiencia práctica de mercado con metodologías de enseñanza ágiles y aplicables.",
            about_desc_2: "Nuestra labor abarca desde el desarrollo de líderes de alto impacto hasta la reestructuración de procesos y planificación de negocios, integrando tecnología, cultura de resultados y una gobernanza sólida.",
            stat_experience: "Años de experiencia",
            stat_leaders: "Líderes formados",
            stat_companies: "Empresas asociadas",
            mvv_label: "Nuestros Pilares",
            mvv_section_title: "Lo que nos mueve y dirige",
            mvv_section_subtitle: "Guiados por propósitos claros, objetivos audaces y valores sólidos para entregar la mejor experiencia de aprendizaje.",
            mvv_missao_title: "Misión",
            mvv_missao_desc: "Prestar servicios de excelencia y buscar, de forma continua y sistemática, satisfacer <br />las necesidades de nuestros clientes, superando sus expectativas y contribuyendo de esta forma a la<br /> generación de valor.",
            mvv_missao_tag: "Propósito &amp; Acción",
            mvv_visao_title: "Visión",
            mvv_visao_desc: "Estar entre las principales empresas del mercado de servicios de consultoría y gestión, y ser una referencia de excelencia en la prestación de servicios de apoyo a la gestión empresarial.",
            mvv_visao_tag: "Enfoque en el Futuro",
            mvv_valores_title: "Valores",
            mvv_valores_desc: "Guiados por la ética, la honestidad y la transparencia en las relaciones. Buscamos la calidad y la excelencia continua con responsabilidad social, enfoque en la sostenibilidad y entrega puntual de resultados.",
            mvv_valores_tag: "Nuestros Principios",
            incompany_label: "Compromiso con el Agronegocio",
            incompany_title: "Conectando Líderes para Fortalecer el Futuro de la Agroindustria",
            incompany_description: "Nuestro compromiso es capacitar a productores e industrias para impulsar la verticalización regional, promoviendo el desarrollo sostenible a través de conexiones estratégicas, tecnología e inteligencia de mercado.",
            incompany_feature_1_title: "Alianzas y Conexiones Estratégicas",
            incompany_feature_1_desc: "Participación activa en debates sectoriales para consolidar alianzas fundamentales para el avance socioeconómico regional.",
            incompany_feature_2_title: "Tecnología Aplicada al Campo",
            incompany_feature_2_desc: "Integración de innovaciones y procesos modernos que amplían la productividad y competitividad del productor rural.",
            incompany_feature_3_title: "Verticalización de la Producción",
            incompany_feature_3_desc: "Apoyo en la planificación industrial para retener valor en la región, transformando la producción primaria en productos manufacturados de alto valor.",
            incompany_feature_4_title: "Desarrollo Sostenible",
            incompany_feature_4_desc: "Estructuración de estrategias inteligentes de mercado que alinean el crecimiento económico con prácticas de preservación a largo plazo.",
            incompany_btn: "Hablar con Nuestro Equipo <i class=\"ph ph-arrow-right\"></i>",
            incompany_vertical_text: "AGRO &amp; INNOVACIÓN",
            platform_label: "App de la Empresa",
            platform_title: "Más practicidad en la <span class=\"text-highlight\">palma de tu mano</span>",
            platform_description: "Con nuestra aplicación, sigues todo lo que necesitas desde donde estés, con seguridad, agilidad y una experiencia completa.",
            platform_feature_1: "Siga su información en tiempo real",
            platform_feature_2: "Informes e indicadores de forma sencilla y rápida",
            platform_feature_3: "Notificaciones importantes a la hora adecuada",
            platform_feature_4: "Seguridad y protección de sus datos",
            cert_label: "Garantía de Excelencia",
            cert_title: "Nuestros Selos e Certificações",
            cert_subtitle: "Nuestras prácticas corporativas y programas de capacitación están respaldados por sellos de excelencia, asegurando el cumplimiento legal, la diversidad, la integridad y la gobernanza de alto nivel.",
            cert_zoom: "<i class=\"ph ph-magnifying-glass-plus\"></i> Ampliar Sello",
            cert_1_title: "Sello Abrangem",
            cert_1_desc: "Estándar nacional reconocido en la gestión y calidad de capacitaciones corporativas de excelencia.",
            cert_2_title: "Certificación LGPD",
            cert_2_desc: "Cumplimiento completo y seguridad de datos auditada bajo las directrices de la legislación nacional.",
            cert_3_title: "Liderazgo Femenino",
            cert_3_desc: "Fomento activo y comprobado a la igualdad de género, equidad e inclusión en el ambiente de trabajo.",
            cert_4_title: "Responsabilidade Social",
            cert_4_desc: "Prácticas sostenibles certificadas de gobernanza ambiental, social y corporativa (ESG).",
            cert_5_title: "Cumplimiento Laboral",
            cert_5_desc: "Rigor ético y cumplimiento legal garantizado en las relaciones laborales y contrataciones.",
            footer_desc: "Educación corporativa, liderazgo y gestión para empresas en crecimiento.",
            footer_links_title: "Links rápidos",
            footer_categories_title: "Categorías",
            footer_contact_title: "Contáctenos",
            team_section_title: "Junta Directiva & Liderazgo",
            team_role_1: "Fundador & CEO",
            team_focus_1: "Planificación, Análisis e Inspecciones Internacionales",
            team_bio_1_p1: "CEO de Axia Group, empresa de consultoría y gestión empresarial que opera en Brasil y en el exterior, y lleva en su ADN visión de futuro, enfoque en resultados y soluciones innovadoras que garantizan los niveles más altos de valor.",
            team_bio_1_p2: "Posee una sólida experiencia y liderazgo en proyectos TAP/PID (project charter / Project Initiation Document) \"proyectos iniciados desde cero\", con especialización en gestión de operaciones de la industria, el comercio y el agronegocio, centrándose en la innovación, la tecnología y la sostenibilidad.",
            team_bio_1_li1: "Licenciado en Administración de Empresas por la Facultad Pitágoras (Campus Linhares - ES).",
            team_bio_1_li2: "MBA en Auditoría, Control y Finanzas Empresariales por la FGV (Fundación Getúlio Vargas).",
            team_bio_1_li3: "Consultor miembro de la clínica de negocios del CRA/ES (Consejo Regional de Administración de Espírito Santo).",
            team_bio_1_li4: "Consultor empresarial registrado en ABRACEM (Asociación Brasileña de Consultores Empresariales).",
            team_cta_schedule: "<i class=\"fa-brands fa-whatsapp\"></i> Agende un Horario",
            team_role_2: "Director de Marketing",
            team_focus_2: "Planificación y Estrategias de Publicidade y Marketing",
            team_bio_2_p1: "Administrador, publicista y emprendedor con fuerte presencia en Brasil y Portugal. Capixaba, reside entre Serra/ES y Lisboa/PT, acumulando más de 25 años de experiencia en los sectores de marketing digital, gestión empresarial y comunicación estratégica.",
            team_bio_2_p2: "Es fundador y CEO de Divulgar Comunicação, agencia de publicidad y marketing digital con sedes en Brasil y Portugal, reconocida por desarrollar soluciones creativas y eficaces que conectan marcas con su público de forma auténtica y estratégica.",
            team_bio_2_p3: "Con un enfoque innovador, trabaja en el desarrollo de proyectos que combinan tradición y modernidad, con foco en la experiencia del cliente y el fortalecimiento de las marcas. Posee especial experiencia en:",
            team_bio_2_li1: "Consultoría en marketing digital y branding.",
            team_bio_2_li2: "Estrategias de presencia digital (Google, redes sociales y comercio electrónico).",
            team_bio_2_li3: "Creación y optimización de sitios web y plataformas digitales.",
            team_bio_2_li4: "Organización de eventos promocionales, alianzas estratégicas y campañas de sorteo nacionales e internacionales.",
            team_cta_click_here: "<i class=\"fa-brands fa-whatsapp\"></i> Haga clic aquí",
            team_role_3: "Director Contable y Jurídico",
            team_focus_3: "Consultoría Contable, Fiscal y Tributaria",
            team_bio_3_p1: "Gilberto Batista se desempeña como Director en Controltech Contabilidade e Auditoria S/A, empresa con fuerte presencia en Brasil y Estados Unidos.",
            team_bio_3_p2: "Al frente de Controltech, lidera un equipo de alto rendimiento especializado en la prestación de servicios integrales en consultoría contábil, fiscal, tributaria, laboral e institucional.",
            team_bio_3_p3: "Con una visión estratégica y enfoque en la excelencia técnica, conduce proyectos que van desde el análisis y la estructuración contable hasta la revisión fiscal y planificación tributaria, garantizando soluciones integradas, cumplimiento legal y apoyo gerencial para empresas de diversos tamaños y segmentos.",
            team_role_4: "Director de Inversiones",
            team_focus_4: "Crédito Estructurado y Relación Bancaria",
            team_bio_4_p1: "Licenciado en Finanzas con una trayectoria consolidada de más de dos décadas en el sector bancario y de consultoria empresarial. Se desempeñó como gerente en importantes instituciones financieras, incluyendo el Banco Francês e Italiano, Banco Sudameris Brasil, Banco Real ABN AMRO, Banco Santander y Banco Original.",
            team_bio_4_p2: "Fundador de NJCA Consultoria, Newton es especialista en estructurar soluciones financieras personalizadas para la obtención de recursos e inversiones corporativas seguras.",
            team_bio_4_p3: "Posee un sólido networking corporativo y se desempeña como socio de consultoría de reconocidas instituciones como Banco Inter, Banco PAN, Banco Bari, Banco CashMe y Caixa Económica Federal. Su misión es apoyar a los empresarios a tomar decisiones más inteligentes y rentables.",
            team_section_title_2: "Alianzas Estratégicas & Mercado Externo",
            team_role_5: "Socio de Alianza Estratégica",
            team_focus_5: "Logística y Comercio Exterior Internacional",
            team_bio_5_p1: "Ado Pereira Alves Belmok tiene formación técnica en Contabilidad y reside en la ciudad de Oporto, en Portugal, desde donde lidera las operaciones internacionales de Exporto Commerce Ltda.",
            team_bio_5_p2: "Como CEO de Exporto Commerce, dirige una operación con presencia global y sede en Cariacica (ES), orientada a la atención estratégica de mercados en América del Norte, América del Sur, Europa y Asia.",
            team_bio_5_p3: "Se ha convertido en un referente en soluciones logísticas y estrategias de exportación, aprobando a empresas brasileñas a llegar a nuevos mercados internacionales de forma segura, destacando en:",
            team_bio_5_li1: "Captación de proveedores en Brasil y clientes en el extranjero.",
            team_bio_5_li2: "Logística completa de exportación y despacho aduanero.",
            team_bio_5_li3: "Recepción, envío, distribución y venta de productos en el mercado internacional.",
            team_cta_speak_expert: "<i class=\"fa-brands fa-whatsapp\"></i> Hablar con el Especialista",
            conduct_page_title: "Código de Conducta - AXIA GROUP | ACADEMY",
            conduct_hero_title: "Código de Conducta",
            conduct_hero_desc: "Nuestros compromisos con la ética, la integridad y la responsabilidad en todas nuestras acciones y relaciones.",
            conduct_sidebar_title: "Navegación",
            conduct_download_title: "Código de Conducta Completo",
            conduct_download_desc: "Descargue la versión oficial en formato PDF para lectura sin conexión.",
            conduct_download_btn: "Descargar PDF",
            conduct_intro_p: "El Código de Conducta de Axia Group expresa nuestros compromisos con la ética, la integridad y la responsabilidad en todas nuestras acciones y relaciones. Orienta el comportamiento de todos los colaboradores, socios, proveedores y partes interesadas, reforzando los valores de nuestra actuación.",
            conduct_nav_1: "Salud y Seguridad",
            conduct_nav_2: "Conflicto de Interés",
            conduct_nav_3: "Contratación de Parientes",
            conduct_nav_4: "Información Confidencial",
            conduct_nav_5: "Relaciones Societarias",
            conduct_nav_6: "Clientes y Proveedores",
            conduct_nav_7: "Sector Público",
            conduct_nav_8: "Relaciones con la Competencia",
            conduct_nav_9: "Relaciones con la Comunidad",
            conduct_nav_10: "Relaciones con los Medios",
            conduct_nav_11: "Sostenibilidad",
            conduct_nav_12: "Protección de Datos",
            conduct_nav_13: "Respeto y Diversidad",
            conduct_nav_14: "Transparencia",
            conduct_nav_15: "Cumplimiento y Penalidades",
            conduct_title_1: "1.1. Salud y Seguridad",
            conduct_title_2: "1.2. Conflicto de Interés",
            conduct_title_3: "1.3. Contratación de Familiares y Parientes",
            conduct_title_4: "1.4. Información Confidencial",
            conduct_title_5: "2. Relaciones con Socios/Accionistas y Consejo Consultivo",
            conduct_title_6: "3. Relaciones con Clientes y Proveedores",
            conduct_title_6_1: "Regalos y Obsequios:",
            conduct_title_6_2: "Interacciones con Clientes:",
            conduct_title_7: "4. Relaciones con el Sector Público",
            conduct_title_8: "5. Relaciones con la Competencia",
            conduct_title_9: "6. Relaciones con la Comunidad",
            conduct_title_10: "7. Relaciones con los Medios",
            conduct_title_11: "8. Sostenibilidad",
            conduct_title_12: "9. Protección de Datos",
            conduct_title_13: "10. Respeto en el Entorno Laboral",
            conduct_title_14: "11. Transparencia",
            conduct_title_15: "12. Cumplimiento y Penalidades",
            ethics_box_title: "Canales de Ética y Cumplimiento",
            ethics_box_desc: "Si tiene alguna duda o desea registrar una queja/denuncia de manera totalmente confidencial y segura, utilice nuestros canales oficiales listados a continuación.",
            ethics_info_title: "Contactos Oficiales",
            ethics_item_email: "Correo electrónico:",
            ethics_item_phone: "Teléfono:",
            ethics_item_web: "Plataforma en línea:",
            ethics_form_title: "Registrar Reclamación",
            ethics_label_name: "Nombre (Opcional)",
            ethics_label_email: "Correo de Contacto (Opcional)",
            ethics_label_msg: "Detalle de la Ocurrencia/Reclamación",
            ethics_btn_submit: "Enviar Reporte",
            contact_hero_title: "Contacto",
            contact_hero_desc: "Estamos listos para atenderle a usted y a su empresa. Elija el canal de su preferencia.",
            contact_general_title: "Preguntas, Alianzas e Información",
            contact_general_desc: "Para hablar de nuestros cursos, programar reuniones, alianzas de negocio u otras preguntas generales.",
            contact_general_form_title: "Enviar Mensaje",
            contact_label_name: "Nombre Completo",
            contact_label_email: "Correo Corporativo",
            contact_label_phone: "Teléfono / WhatsApp",
            contact_label_msg: "Mensaje o Pregunta",
            contact_btn_send: "Enviar Mensaje",
            contact_info_office: "Nuestras Oficinas",
            contact_form_intro: "Complete el formulario y nos pondremos en contacto en breve."
        },
        en: {
            nav_home: "Home",
            nav_courses: "Courses",
            nav_about: "About Us",
            nav_team: "Team",
            nav_conduct: "Code of Conduct",
            nav_contact: "Contact",
            btn_login: "Login",
            btn_speak_team: "Speak with the Team",
            hero_title: "Corporate education, leadership<br />and management for growing<br /><span class=\"text-accent\">companies.</span>",
            hero_desc: "Online courses and in-person experiences that develop<br />people, strengthen leaders, and drive results.",
            hero_btn_explore: "Explore Courses <i class=\"ph ph-arrow-right\"></i>",
            hero_benefit_1: "100% Online &amp;<br />In-Person Courses",
            hero_benefit_2: "Expert<br />Instructors",
            hero_benefit_3: "Content Applicable<br />to your Reality",
            hero_benefit_4: "Recognized<br />Certificate",
            hero_mobile_title: "Knowledge<br />that <span class=\"text-accent\">transforms.</span><br />Results that<br /><span class=\"text-accent\">drive.</span>",
            hero_mobile_desc: "Practical, updated and strategic training for you to evolve, lead and generate impact in the market.",
            hero_mobile_btn: "Discover our courses <i class=\"ph ph-arrow-right\"></i>",
            hero_mobile_benefit_1: "Updated<br />content",
            hero_mobile_benefit_2: "Applicable<br />learning",
            hero_mobile_benefit_3: "Recognized<br />certificates",
            hero_mobile_benefit_4: "Active<br />community",
            hero_mobile_footer_1: "LEARN FROM <span class=\"text-accent-alt\">EXPERTS</span>",
            hero_mobile_footer_2: "APPLY IN <span class=\"text-accent-alt\">PRACTICE</span>",
            hero_mobile_footer_3: "EVOLVE <span class=\"text-accent-alt\">ALWAYS</span>",
            trilhas_section_title: "Our Tracks",
            trilhas_see_all: "See all courses <i class=\"ph ph-arrow-right\"></i>",
            trilha_1_title: "Leadership",
            trilha_1_desc: "Develop inspiring leaders and high-performance teams.",
            trilha_2_title: "People Management",
            trilha_2_desc: "Engagement, culture and performance that generate value.",
            trilha_3_title: "Strategic Planning",
            trilha_3_desc: "Transform strategy into action and sustainable results.",
            trilha_4_title: "Point of Sale Merchandising",
            trilha_4_desc: "Techniques and practices to boost sales and point-of-sale experience.",
            trilha_5_title: "Human Development",
            trilha_5_desc: "Self-knowledge, communication and emotional intelligence.",
            about_label: "About Us",
            about_title: "Transforming the potential of leaders and organizations into <span class=\"text-accent\">real results.</span>",
            about_desc_1: "AXIA GROUP | ACADEMY is a corporate education ecosystem focused on boosting the performance of medium and large enterprises. We combine practical market experience with agile and applicable teaching methodologies.",
            about_desc_2: "Our operations span from high-impact leadership development to process restructuring and business planning, integrating technology, a culture of results, and solid governance.",
            stat_experience: "Years of experience",
            stat_leaders: "Trained leaders",
            stat_companies: "Partner companies",
            mvv_label: "Our Pillars",
            mvv_section_title: "What moves and guides us",
            mvv_section_subtitle: "Guided by clear purposes, bold objectives and solid values to deliver the best learning experience.",
            mvv_missao_title: "Mission",
            mvv_missao_desc: "Provide services of excellence and seek, in a continuous and systematic way, to meet <br />our clients' needs, exceeding their expectations and thus contributing to<br /> value generation.",
            mvv_missao_tag: "Purpose &amp; Action",
            mvv_visao_title: "Vision",
            mvv_visao_desc: "Be among the leading companies in the consulting and management services market, and be a reference of excellence in providing support services to business management.",
            mvv_visao_tag: "Future Focus",
            mvv_valores_title: "Values",
            mvv_valores_desc: "Guided by ethics, honesty and transparency in relationships. We seek quality and continuous excellence with social responsibility, a focus on sustainability and on-time delivery of results.",
            mvv_valores_tag: "Our Principles",
            incompany_label: "Commitment to Agribusiness",
            incompany_title: "Connecting Leaders to Strengthen the Future of Agribusiness",
            incompany_description: "Our commitment is to empower producers and industries to boost regional verticalization, promoting sustainable development through strategic connections, technology, and market intelligence.",
            incompany_feature_1_title: "Strategic Alliances and Connections",
            incompany_feature_1_desc: "Active participation in sector debates to consolidate essential partnerships for regional socio-economic advancement.",
            incompany_feature_2_title: "Technology Applied to the Field",
            incompany_feature_2_desc: "Integration of innovations and modern processes that enhance the rural producer's productivity and competitiveness.",
            incompany_feature_3_title: "Production Verticalization",
            incompany_feature_3_desc: "Support in industrial planning to retain value in the region, transforming primary production into high-value manufactured products.",
            incompany_feature_4_title: "Sustainable Development",
            incompany_feature_4_desc: "Structuring of smart market strategies that align economic growth with long-term preservation practices.",
            incompany_btn: "Speak with Our Team <i class=\"ph ph-arrow-right\"></i>",
            incompany_vertical_text: "AGRO &amp; INNOVATION",
            platform_label: "Company App",
            platform_title: "More convenience in the <span class=\"text-highlight\">palm of your hand</span>",
            platform_description: "With our app, you track everything you need from wherever you are, with security, agility, and a complete experience.",
            platform_feature_1: "Track your information in real time",
            platform_feature_2: "Reports and indicators in a simple and fast way",
            platform_feature_3: "Important notifications at the right time",
            platform_feature_4: "Security and protection of your data",
            cert_label: "Guarantee of Excellence",
            cert_title: "Our Badges and Certifications",
            cert_subtitle: "Our corporate practices and training programs are endorsed by quality seals of excellence, ensuring legal compliance, diversity, integrity, and high-level governance.",
            cert_zoom: "<i class=\"ph ph-magnifying-glass-plus\"></i> Zoom Badge",
            cert_1_title: "Abrangem Badge",
            cert_1_desc: "National standard recognized in the management and quality of corporate training of excellence.",
            cert_2_title: "LGPD Certification",
            cert_2_desc: "Complete compliance and data security audited under the guidelines of national legislation.",
            cert_3_title: "Female Leadership",
            cert_3_desc: "Active and proven support for gender equality, equity, and inclusion in the workplace.",
            cert_4_title: "Social Responsibility",
            cert_4_desc: "Certified sustainable practices of environmental, social, and corporate governance (ESG).",
            cert_5_title: "Labor Compliance",
            cert_5_desc: "Ethical rigor and guaranteed legal compliance in labor relations and hiring.",
            footer_desc: "Corporate education, leadership, and management for growing companies.",
            footer_links_title: "Quick Links",
            footer_categories_title: "Categories",
            footer_contact_title: "Get in Touch",
            team_section_title: "Board of Directors & Leadership",
            team_role_1: "Founder & CEO",
            team_focus_1: "International Planning, Analysis & Inspections",
            team_bio_1_p1: "CEO of Axia Group, a business consulting and management firm operating in Brazil and abroad, with a DNA of future vision, focus on results, and innovative solutions that guarantee the highest levels of value.",
            team_bio_1_p2: "Possesses solid experience and leadership in TAP/PID (project charter / Project Initiation Document) projects \"started from scratch\", with specialization in operation management across industry, trade, and agribusiness, focusing on innovation, technology, and sustainability.",
            team_bio_1_li1: "Bachelor of Business Administration from Faculdade Pitágoras (Linhares Campus - ES).",
            team_bio_1_li2: "MBA in Auditing, Controlling & Corporate Finance from FGV (Fundação Getúlio Vargas).",
            team_bio_1_li3: "Consultant member of the CRA/ES Business Clinic (Regional Council of Administration of Espírito Santo).",
            team_bio_1_li4: "Business consultant registered with ABRACEM (Brazilian Association of Business Consultants).",
            team_cta_schedule: "<i class=\"fa-brands fa-whatsapp\"></i> Schedule a Meeting",
            team_role_2: "Marketing Director",
            team_focus_2: "Advertising & Marketing Planning and Strategies",
            team_bio_2_p1: "Administrator, advertiser and entrepreneur with a strong presence in Brazil and Portugal. Born in Espírito Santo, resides between Serra/ES and Lisbon/PT, accumulating more than 25 years of experience in the digital marketing, business management and strategic communication sectors.",
            team_bio_2_p2: "He is the founder and CEO of Divulgar Comunicação, an advertising and digital marketing agency with offices in Brazil and Portugal, recognized for developing creative and effective solutions that connect brands to their audience in an authentic and strategic way.",
            team_bio_2_p3: "With an innovative approach, he works in the development of projects that combine tradition and modernity, focusing on client experience and brand strengthening. He has special expertise in:",
            team_bio_2_li1: "Consulting in digital marketing and branding.",
            team_bio_2_li2: "Digital presence strategies (Google, social media and e-commerce).",
            team_bio_2_li3: "Creation and optimization of websites and digital platforms.",
            team_bio_2_li4: "Organization of promotional events, strategic partnerships and national and international sweepstake campaigns.",
            team_cta_click_here: "<i class=\"fa-brands fa-whatsapp\"></i> Click Here",
            team_role_3: "Accounting & Legal Director",
            team_focus_3: "Accounting, Fiscal & Tax Consulting",
            team_bio_3_p1: "Gilberto Batista serves as Director at Controltech Contabilidade e Auditoria S/A, a company with a strong presence in Brazil and the United States.",
            team_bio_3_p2: "Leading Controltech, he heads a high-performance team specialized in providing complete services in accounting, fiscal, tax, labor and institutional consulting.",
            team_bio_3_p3: "With a strategic vision and focus on technical excellence, he leads projects that involve everything from accounting analysis and structuring to fiscal review and tax planning, ensuring integrated solutions, legal compliance and management support for companies of various sizes and segments.",
            team_role_4: "Investment Director",
            team_focus_4: "Structured Credit & Banking Relationship",
            team_bio_4_p1: "Graduated in Finance with a consolidated trajectory of more than two decades in the banking and business consulting sector. Served as manager at major financial institutions, including Banco Francês e Italiano, Banco Sudameris Brasil, Banco Real ABN AMRO, Banco Santander and Banco Original.",
            team_bio_4_p2: "Founder of NJCA Consultoria, Newton is an specialist in structuring customized financial solutions for raising capital and secure corporate investments.",
            team_bio_4_p3: "Has a solid corporate networking and acts as a consulting partner for renowned institutions such as Banco Inter, Banco PAN, Banco Bari, Banco CashMe and Caixa Econômica Federal. His mission is to assist entrepreneurs in making smarter and more profitable decisions.",
            team_section_title_2: "Board of Directors & Leadership",
            team_role_5: "Strategic Alliance Partner",
            team_focus_5: "International Logistics & Foreign Trade",
            team_bio_5_p1: "Ado Pereira Alves Belmok has technical training in Accounting and resides in the city of Porto, Portugal, from where he leads the international operations of Exporto Commerce Ltda.",
            team_bio_5_p2: "As CEO of Exporto Commerce, he leads an operation with global presence and headquarters in Cariacica (ES), aimed at the strategic service of markets in North America, South America, Europe, and Asia.",
            team_bio_5_p3: "He has become a reference in logistics solutions and export strategies, supporting Brazilian companies in reaching new international markets safely, with highlight in:",
            team_bio_5_li1: "Sourcing of suppliers in Brazil and clients abroad.",
            team_bio_5_li2: "Full export logistics and customs clearance.",
            team_bio_5_li3: "Receiving, shipping, distribution and sales of products in the international market.",
            team_cta_speak_expert: "<i class=\"fa-brands fa-whatsapp\"></i> Talk to the Specialist",
            conduct_page_title: "Code of Conduct - AXIA GROUP | ACADEMY",
            conduct_hero_title: "Code of Conduct",
            conduct_hero_desc: "Our commitments to ethics, integrity, and responsibility in all our actions and relationships.",
            conduct_sidebar_title: "Navigation",
            conduct_download_title: "Complete Code of Conduct",
            conduct_download_desc: "Download the official version in PDF format for offline reading.",
            conduct_download_btn: "Download PDF",
            conduct_intro_p: "The Axia Group Code of Conduct expresses our commitments to ethics, integrity, and responsibility in all our actions and relationships. It guides the behavior of all employees, partners, shareholders, suppliers, and stakeholders, reinforcing the values of our business.",
            conduct_nav_1: "Health & Safety",
            conduct_nav_2: "Conflicts of Interest",
            conduct_nav_3: "Hiring of Relatives",
            conduct_nav_4: "Confidential Information",
            conduct_nav_5: "Corporate Relations",
            conduct_nav_6: "Clients & Suppliers",
            conduct_nav_7: "Public Sector",
            conduct_nav_8: "Relations with Competitors",
            conduct_nav_9: "Community Relations",
            conduct_nav_10: "Media Relations",
            conduct_nav_11: "Sustainability",
            conduct_nav_12: "Data Protection",
            conduct_nav_13: "Respect & Diversity",
            conduct_nav_14: "Transparency",
            conduct_nav_15: "Compliance & Penalties",
            conduct_title_1: "1.1. Health & Safety",
            conduct_title_2: "1.2. Conflicts of Interest",
            conduct_title_3: "1.3. Hiring of Family Members and Relatives",
            conduct_title_4: "1.4. Confidential Information",
            conduct_title_5: "2. Relations with Partners/Shareholders and Advisory Board",
            conduct_title_6: "3. Relations with Clients and Suppliers",
            conduct_title_6_1: "Gifts and Favors:",
            conduct_title_6_2: "Interactions with Clients:",
            conduct_title_7: "4. Relations with the Public Sector",
            conduct_title_8: "5. Relations with Competitors",
            conduct_title_9: "6. Relations with the Community",
            conduct_title_10: "7. Relations with the Media",
            conduct_title_11: "8. Sustainability",
            conduct_title_12: "9. Data Protection",
            conduct_title_13: "10. Respect in the Workplace",
            conduct_title_14: "11. Transparency",
            conduct_title_15: "12. Compliance and Penalties",
            ethics_box_title: "Ethics & Compliance Channels",
            ethics_box_desc: "If you have any questions or wish to register a formal complaint/report in a fully confidential and secure manner, please use our official channels listed below.",
            ethics_info_title: "Official Contacts",
            ethics_item_email: "Email:",
            ethics_item_phone: "Phone:",
            ethics_item_web: "Online Platform:",
            ethics_form_title: "Register Complaint",
            ethics_label_name: "Name (Optional)",
            ethics_label_email: "Contact Email (Optional)",
            ethics_label_msg: "Report Details/Complaint",
            ethics_btn_submit: "Submit Report",
            contact_hero_title: "Contact Us",
            contact_hero_desc: "We are ready to assist you and your company. Choose your preferred channel.",
            contact_general_title: "Questions, Partnerships and Information",
            contact_general_desc: "To talk about our courses, schedule meetings, business partnerships or other general questions.",
            contact_general_form_title: "Send Message",
            contact_label_name: "Full Name",
            contact_label_email: "Corporate Email",
            contact_label_phone: "Phone / WhatsApp",
            contact_label_msg: "Message or Question",
            contact_btn_send: "Send Message",
            contact_info_office: "Our Offices",
            contact_form_intro: "Fill out the form and we will get in touch shortly."
        }
    };

    function changeLanguage(lang) {
        localStorage.setItem('axia_lang', lang);
        document.documentElement.lang = lang === 'pt' ? 'pt-BR' : (lang === 'es' ? 'es-ES' : 'en-US');
        
        // Update flag active classes
        document.querySelectorAll('.language-selector .lang-flag').forEach(flag => {
            if (flag.getAttribute('data-lang') === lang) {
                flag.classList.add('active');
            } else {
                flag.classList.remove('active');
            }
        });
        
        // Update all translatable elements
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (translations[lang] && translations[lang][key] !== undefined) {
                el.innerHTML = translations[lang][key];
            }
        });
    }

    // Initialize translation engine
    const savedLang = localStorage.getItem('axia_lang') || 'pt';
    changeLanguage(savedLang);

    // Bind flag click events
    document.querySelectorAll('.language-selector .lang-flag').forEach(flag => {
        flag.addEventListener('click', (e) => {
            e.preventDefault();
            const lang = flag.getAttribute('data-lang');
            if (lang) {
                changeLanguage(lang);
            }
        });
    });

});